services:
  java:
    build:
      context: .
      dockerfile: DockerfileJava
    container_name: java-container
    ports:
      - "${TOMCAT_PORT}:8080"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}      
      JAVA_ENV: ${JAVA_ENV}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge



