services:
  flask:
    build:
      context: .
      dockerfile: DockerfilePython
    container_name: flask-app
    ports:
      - "${FLASK_PORT}:5000"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - WTF_CSRF_SECRET_KEY=${WTF_CSRF_SECRET_KEY}
    volumes:
      - ./python-demo:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge



